const { z } = require('zod');

// Optional email styling accepted by spa appointment create/update and by
// create_event_inquiry. Values come from the venue's website; OTA relays
// them (or keeps them on the enquiry row until the thread is done).
const BRANDING_SCHEMA = z.object({
  logo_url: z.string().optional().describe('http(s) image URL shown at the top of the email'),
  brand_color: z.string().optional().describe('Hex accent colour, e.g. #c9a85c'),
  header_bg: z.string().optional().describe('Hex background behind the logo, e.g. #ffffff -- keeps dark logos visible in dark mode'),
}).optional();

function createTools(apiRequest) {
  return [
  {
    name: 'search_availability',
    description: 'Search available room types for a date range and party size',
    inputSchema: {
      check_in: z.string().describe('YYYY-MM-DD'),
      check_out: z.string().describe('YYYY-MM-DD'),
      guests: z.number().int(),
    },
    run: (args) => apiRequest('GET', '/api/availability/search', { query: args }),
  },
  {
    name: 'lookup_guest',
    description: 'Look up a guest by email',
    inputSchema: { email: z.string() },
    run: (args) => apiRequest('GET', '/api/guests/lookup', { query: args }),
  },
  {
    name: 'list_bookings',
    description: 'List bookings, optionally filtered by status, guest, or date range',
    inputSchema: {
      status: z.string().optional(),
      guest_id: z.string().optional(),
      from: z.string().optional(),
      to: z.string().optional(),
    },
    run: (args) => apiRequest('GET', '/api/bookings', { query: args }),
  },
  {
    name: 'get_booking',
    description: 'Get a booking by id',
    inputSchema: { id: z.string() },
    run: ({ id }) => apiRequest('GET', `/api/bookings/${id}`),
  },
  {
    name: 'cancel_booking',
    description: 'Cancel a booking and restore its room availability',
    inputSchema: { id: z.string() },
    run: ({ id }) => apiRequest('DELETE', `/api/bookings/${id}`),
  },
  {
    name: 'list_rooms',
    description: 'List rooms, optionally filtered by room type',
    inputSchema: { room_type_id: z.string().optional() },
    run: (args) => apiRequest('GET', '/api/rooms', { query: args }),
  },
  {
    name: 'create_room',
    description: 'Create a room',
    inputSchema: {
      room_type_id: z.string(),
      room_number: z.string(),
      floor: z.number().int().optional(),
    },
    run: (args) => apiRequest('POST', '/api/rooms', { body: args }),
  },
  {
    name: 'update_room',
    description: 'Update a room',
    inputSchema: {
      id: z.string(),
      room_number: z.string().optional(),
      floor: z.number().int().optional(),
      status: z.enum(['active', 'maintenance', 'inactive']).optional(),
    },
    run: ({ id, ...body }) => apiRequest('PUT', `/api/rooms/${id}`, { body }),
  },
  {
    name: 'list_room_types',
    description: 'List all room types',
    inputSchema: {},
    run: () => apiRequest('GET', '/api/room-types'),
  },
  {
    name: 'create_room_type',
    description: 'Create a room type',
    inputSchema: {
      name: z.string(),
      description: z.string().optional(),
      max_occupancy: z.number().int(),
      base_rate: z.number(),
    },
    run: (args) => apiRequest('POST', '/api/room-types', { body: args }),
  },
  {
    name: 'update_room_type',
    description: 'Update a room type. Set status to "inactive" to delete it — there is no hard-delete endpoint.',
    inputSchema: {
      id: z.string(),
      name: z.string().optional(),
      description: z.string().optional(),
      max_occupancy: z.number().int().optional(),
      base_rate: z.number().optional(),
      status: z.enum(['active', 'inactive']).optional(),
      floor_plan: z.record(z.any()).optional().describe('{ rooms: [{id, type, label, x, y, w, h, sqm?, imgUrl?}], items: [{id, asset, x, y, w, h}], w, h }'),
    },
    run: ({ id, ...body }) => apiRequest('PUT', `/api/room-types/${id}`, { body }),
  },
  {
    name: 'upsert_room_availability',
    description: "Bulk set a room's availability and rates for specific dates",
    inputSchema: {
      room_id: z.string(),
      dates: z.array(z.object({
        date: z.string(),
        is_available: z.boolean().optional(),
        override_rate: z.number().optional(),
        block_reason: z.string().optional(),
      })),
    },
    run: ({ room_id, dates }) => apiRequest('PUT', `/api/availability/rooms/${room_id}`, { body: { dates } }),
  },
  {
    name: 'list_room_type_rates',
    description: "List a room type's dated nightly rates. Dates without a row fall back to base_rate; a per-room override_rate still wins over these.",
    inputSchema: {
      room_type_id: z.string(),
      from: z.string().optional().describe('YYYY-MM-DD, inclusive'),
      to: z.string().optional().describe('YYYY-MM-DD, exclusive'),
    },
    run: ({ room_type_id, ...query }) => apiRequest('GET', `/api/room-types/${room_type_id}/rates`, { query }),
  },
  {
    name: 'upsert_room_type_rates',
    description: "Set a room type's nightly rate over date ranges (to is exclusive, like check_out). rate: null clears the range back to base_rate. A per-room override_rate still takes precedence.",
    inputSchema: {
      room_type_id: z.string(),
      rates: z.array(z.object({
        from: z.string().describe('YYYY-MM-DD, inclusive'),
        to: z.string().describe('YYYY-MM-DD, exclusive'),
        rate: z.number().nullable().describe('Nightly rate > 0, or null to delete the dated rates in range'),
      })),
    },
    run: ({ room_type_id, rates }) => apiRequest('PUT', `/api/room-types/${room_type_id}/rates`, { body: { rates } }),
  },
  {
    name: 'list_restaurants',
    description: 'List all restaurants',
    inputSchema: {},
    run: () => apiRequest('GET', '/api/restaurant'),
  },
  {
    name: 'create_restaurant',
    description: 'Create a restaurant',
    inputSchema: {
      name: z.string(),
      description: z.string().optional(),
      phone: z.string().optional(),
      slot_interval_minutes: z.number().int().optional(),
      default_duration_minutes: z.number().int(),
      closed_days: z.array(z.number().int().min(1).max(7)).optional(),
      currency: z.string().optional().describe('ISO 4217 code, e.g. GBP. Omit to inherit the property\'s currency'),
      timezone: z.string().optional().describe('IANA timezone name, e.g. Europe/London. Omit to inherit the property\'s timezone'),
      payment_protection: z.enum(['none', 'hold', 'deposit']).optional().describe('Whether a reservation requires a card hold or upfront deposit. Defaults to "none"'),
      payment_protection_amount: z.number().min(0).optional().describe('Amount for the hold/deposit, in the restaurant\'s currency'),
    },
    run: (args) => apiRequest('POST', '/api/restaurant', { body: args }),
  },
  {
    name: 'get_restaurant',
    description: 'Get a restaurant by id',
    inputSchema: { id: z.string() },
    run: ({ id }) => apiRequest('GET', `/api/restaurant/${id}`),
  },
  {
    name: 'update_restaurant',
    description: 'Update a restaurant',
    inputSchema: {
      id: z.string(),
      name: z.string().optional(),
      description: z.string().optional(),
      phone: z.string().optional(),
      slot_interval_minutes: z.number().int().optional(),
      default_duration_minutes: z.number().int().optional(),
      closed_days: z.array(z.number().int().min(1).max(7)).optional(),
      status: z.enum(['active', 'inactive']).optional(),
      currency: z.string().optional(),
      timezone: z.string().optional(),
      floor_plan: z.record(z.any()).optional().describe('{ tables: [{otaId, number, seats, x, y, shape}], w, h }'),
      payment_protection: z.enum(['none', 'hold', 'deposit']).optional().describe('Whether a reservation requires a card hold or upfront deposit'),
      payment_protection_amount: z.number().min(0).optional().describe('Amount for the hold/deposit, in the restaurant\'s currency'),
      website_id: z.string().uuid().nullable().optional().describe('One of the property\'s websites (GET /api/property/websites) that table QR codes link to; null to clear'),
    },
    run: ({ id, ...body }) => apiRequest('PUT', `/api/restaurant/${id}`, { body }),
  },
  {
    name: 'list_restaurant_reservations',
    description: 'List reservations for a restaurant, optionally filtered by date, status, or guest',
    inputSchema: {
      restaurant_id: z.string(),
      date: z.string().optional().describe('Exact reservation_date match'),
      date_from: z.string().optional().describe('Inclusive range start, independent of date'),
      date_to: z.string().optional().describe('Inclusive range end, independent of date'),
      status: z.string().optional(),
      guest_id: z.string().optional(),
      clerk_user_id: z.string().optional(),
    },
    run: ({ restaurant_id, ...query }) => apiRequest('GET', `/api/restaurant/${restaurant_id}/reservations`, { query }),
  },
  {
    name: 'get_restaurant_reservation',
    description: 'Get a restaurant reservation by id',
    inputSchema: { restaurant_id: z.string(), id: z.string() },
    run: ({ restaurant_id, id }) => apiRequest('GET', `/api/restaurant/${restaurant_id}/reservations/${id}`),
  },
  {
    name: 'update_restaurant_reservation',
    description: 'Update a restaurant reservation (e.g. set status to "cancelled" to cancel it)',
    inputSchema: {
      restaurant_id: z.string(),
      id: z.string(),
      status: z.string().optional(),
      notes: z.string().optional(),
      contact_name: z.string().optional(),
      contact_email: z.string().optional(),
      contact_phone: z.string().optional(),
      metadata: z.record(z.any()).optional(),
      stripe_payment_intent_id: z.string().optional().describe('Deposit/prepayment charge this reservation is linked to, if any'),
    },
    run: ({ restaurant_id, id, ...body }) => apiRequest('PUT', `/api/restaurant/${restaurant_id}/reservations/${id}`, { body }),
  },
  {
    name: 'update_tour_slot',
    description: 'Update a tour slot\'s status (e.g. set to "inactive" to hide it from search without deleting it)',
    inputSchema: { id: z.string(), status: z.string() },
    run: ({ id, status }) => apiRequest('PUT', `/api/tours/slots/${id}`, { body: { status } }),
  },
  {
    name: 'list_restaurant_tables',
    description: 'List tables for a restaurant',
    inputSchema: { restaurant_id: z.string() },
    run: ({ restaurant_id }) => apiRequest('GET', `/api/restaurant/${restaurant_id}/tables`),
  },
  {
    name: 'create_restaurant_table',
    description: 'Create a table for a restaurant',
    inputSchema: { restaurant_id: z.string(), table_number: z.string(), seats: z.number().int(), location: z.string().optional() },
    run: ({ restaurant_id, ...body }) => apiRequest('POST', `/api/restaurant/${restaurant_id}/tables`, { body }),
  },
  {
    name: 'update_restaurant_table',
    description: 'Update a restaurant table',
    inputSchema: { restaurant_id: z.string(), id: z.string(), table_number: z.string().optional(), seats: z.number().int().optional(), location: z.string().optional(), status: z.enum(['active', 'inactive']).optional() },
    run: ({ restaurant_id, id, ...body }) => apiRequest('PUT', `/api/restaurant/${restaurant_id}/tables/${id}`, { body }),
  },
  {
    name: 'list_restaurant_menu',
    description: 'List menu items for room/table service, optionally filtered by restaurant or category',
    inputSchema: {
      restaurant_id: z.string().optional(),
      category: z.string().optional(),
    },
    run: (query) => apiRequest('GET', '/api/restaurant-orders/menu', { query }),
  },
  {
    name: 'create_restaurant_menu_item',
    description: 'Create a menu item for room/table service',
    inputSchema: {
      name: z.string(),
      description: z.string().optional(),
      category: z.string().optional(),
      price: z.number(),
      restaurant_id: z.string().optional().describe('Omit for a property-wide item not tied to one restaurant'),
      allergens: z.array(z.string()).optional(),
      variants: z.array(z.string()).optional().describe('e.g. ["Small", "Large"], ["Mild", "Hot"]'),
      translations: z.record(z.object({ name: z.string().optional(), description: z.string().optional() }))
        .optional()
        .describe('Keyed by language code, e.g. { "fr": { "name": "...", "description": "..." } }'),
    },
    run: (args) => apiRequest('POST', '/api/restaurant-orders/menu', { body: args }),
  },
  {
    name: 'update_restaurant_menu_item',
    description: 'Update a menu item. Set status to "inactive" to delete it — there is no hard-delete endpoint.',
    inputSchema: {
      id: z.string(),
      name: z.string().optional(),
      description: z.string().optional(),
      category: z.string().optional(),
      price: z.number().optional(),
      restaurant_id: z.string().optional(),
      allergens: z.array(z.string()).optional(),
      variants: z.array(z.string()).optional().describe('e.g. ["Small", "Large"], ["Mild", "Hot"]'),
      translations: z.record(z.object({ name: z.string().optional(), description: z.string().optional() }))
        .optional()
        .describe('Keyed by language code -- replaces the whole object, not a per-language merge'),
      status: z.enum(['active', 'inactive']).optional(),
    },
    run: ({ id, ...body }) => apiRequest('PUT', `/api/restaurant-orders/menu/${id}`, { body }),
  },
  {
    name: 'bulk_delete_restaurant_menu_items',
    description: 'Soft-delete multiple menu items at once by setting their status to "inactive" — there is no hard-delete endpoint',
    inputSchema: { ids: z.array(z.string()).min(1) },
    run: (args) => apiRequest('PUT', '/api/restaurant-orders/menu/bulk-delete', { body: args }),
  },
  {
    name: 'rename_restaurant_menu_category',
    description: 'Rename a menu category on every item that has it, e.g. to merge duplicates like "cocktail" and "Cocktails" into one name',
    inputSchema: {
      restaurant_id: z.string().optional().describe('Omit to rename across every restaurant on the property'),
      from: z.string(),
      to: z.string(),
    },
    run: (args) => apiRequest('PUT', '/api/restaurant-orders/menu/rename-category', { body: args }),
  },
  {
    name: 'get_restaurant_service_periods',
    description: "List a restaurant's service periods (bookable windows)",
    inputSchema: { restaurant_id: z.string() },
    run: ({ restaurant_id }) => apiRequest('GET', `/api/restaurant/${restaurant_id}/service-periods`),
  },
  {
    name: 'set_restaurant_service_periods',
    description: "Replace all of a restaurant's service periods",
    inputSchema: {
      restaurant_id: z.string(),
      periods: z.array(z.object({
        label: z.string().optional(),
        start_time: z.string(),
        end_time: z.string(),
      })),
    },
    run: ({ restaurant_id, periods }) => apiRequest('PUT', `/api/restaurant/${restaurant_id}/service-periods`, { body: { periods } }),
  },
  {
    name: 'list_proshop_shops',
    description: 'List pro shops',
    inputSchema: {},
    run: () => apiRequest('GET', '/api/proshop/shops'),
  },
  {
    name: 'create_proshop_shop',
    description: 'Create a pro shop',
    inputSchema: {
      name: z.string(),
      description: z.string().optional(),
    },
    run: (args) => apiRequest('POST', '/api/proshop/shops', { body: args }),
  },
  {
    name: 'update_proshop_shop',
    description: 'Update a pro shop. Set status to "inactive" to delete it — there is no hard-delete endpoint.',
    inputSchema: {
      id: z.string(),
      name: z.string().optional(),
      description: z.string().optional(),
      status: z.enum(['active', 'inactive']).optional(),
    },
    run: ({ id, ...body }) => apiRequest('PUT', `/api/proshop/shops/${id}`, { body }),
  },
  {
    name: 'list_proshop_items',
    description: 'List pro shop catalogue items, optionally filtered by shop or category',
    inputSchema: {
      shop_id: z.string().optional(),
      category: z.string().optional(),
    },
    run: (args) => apiRequest('GET', '/api/proshop/items', { query: args }),
  },
  {
    name: 'create_proshop_item',
    description: 'Create a pro shop catalogue item',
    inputSchema: {
      shop_id: z.string(),
      name: z.string(),
      description: z.string().optional(),
      category: z.string().optional(),
      price: z.number(),
    },
    run: (args) => apiRequest('POST', '/api/proshop/items', { body: args }),
  },
  {
    name: 'update_proshop_item',
    description: 'Update a pro shop catalogue item. Set status to "inactive" to delete it — there is no hard-delete endpoint.',
    inputSchema: {
      id: z.string(),
      name: z.string().optional(),
      description: z.string().optional(),
      category: z.string().optional(),
      price: z.number().optional(),
      status: z.enum(['active', 'inactive']).optional(),
    },
    run: ({ id, ...body }) => apiRequest('PUT', `/api/proshop/items/${id}`, { body }),
  },
  {
    name: 'list_proshop_booking_items',
    description: 'List pro shop items added to a golf booking',
    inputSchema: { booking_id: z.string() },
    run: ({ booking_id }) => apiRequest('GET', `/api/proshop/booking/${booking_id}`),
  },
  {
    name: 'add_proshop_booking_item',
    description: 'Add a pro shop catalogue item to a golf booking',
    inputSchema: {
      booking_id: z.string(),
      item_id: z.string(),
      quantity: z.number().int().optional(),
    },
    run: ({ booking_id, ...body }) => apiRequest('POST', `/api/proshop/booking/${booking_id}`, { body }),
  },
  {
    name: 'remove_proshop_booking_item',
    description: 'Remove a pro shop item from a golf booking',
    inputSchema: { booking_id: z.string(), id: z.string() },
    run: ({ booking_id, id }) => apiRequest('DELETE', `/api/proshop/booking/${booking_id}/${id}`),
  },
  {
    name: 'list_event_inquiries',
    description: 'List event inquiries for this property',
    inputSchema: {},
    run: () => apiRequest('GET', '/api/event-inquiries'),
  },
  {
    name: 'create_event_inquiry',
    description: 'Create an event or general inquiry (event_date is optional)',
    inputSchema: {
      name: z.string(),
      email: z.string(),
      phone: z.string().optional(),
      event_date: z.string().optional().describe('YYYY-MM-DD; omit for a general enquiry with no date'),
      guests: z.number().int().optional(),
      event_type: z.string().optional(),
      format: z.string().optional(),
      message: z.string().optional(),
      restaurant_id: z.string().optional(),
      spa_id: z.string().optional().describe('Which spa this enquiry is about; needed for the AI reply to propose and book a slot'),
      branding: BRANDING_SCHEMA.describe('Styles the confirmation email if the AI reply books a slot; kept only for this enquiry'),
      cancel_url: z.string().optional().describe('http(s) URL for the guest to cancel; may contain {id}, filled in when booked'),
    },
    run: (args) => apiRequest('POST', '/api/event-inquiries', { body: args }),
  },
  {
    name: 'update_event_inquiry',
    description: 'Update an event inquiry\'s status, restaurant assignment, event details, or guest contact info',
    inputSchema: {
      id: z.string(),
      status: z.string().optional(),
      restaurant_id: z.string().optional(),
      event_date: z.string().optional().describe('YYYY-MM-DD'),
      event_time: z.string().optional().describe('HH:MM'),
      guests: z.number().int().optional(),
      name: z.string().optional(),
      email: z.string().optional(),
      phone: z.string().optional(),
    },
    run: ({ id, ...body }) => apiRequest('PUT', `/api/event-inquiries/${id}`, { body }),
  },
  {
    name: 'list_event_inquiry_replies',
    description: 'List the reply thread for an event inquiry',
    inputSchema: { id: z.string() },
    run: ({ id }) => apiRequest('GET', `/api/event-inquiries/${id}/replies`),
  },
  {
    name: 'create_event_inquiry_reply',
    description: 'Send a reply on an event inquiry (emails the guest and moves status to "contacted" if it was "new")',
    inputSchema: { id: z.string(), body: z.string() },
    run: ({ id, body }) => apiRequest('POST', `/api/event-inquiries/${id}/replies`, { body: { body } }),
  },
  {
    name: 'list_ai_drafts',
    description: 'List AI-drafted event inquiry replies across the property (approval queue). Defaults to pending; each draft carries a 0-100 quality_score, requires_human + reason, and a summary',
    inputSchema: { status: z.enum(['pending', 'sending', 'sent', 'rejected', 'superseded', 'failed']).optional() },
    run: ({ status }) => apiRequest('GET', `/api/event-inquiries/ai-drafts${status ? `?status=${status}` : ''}`),
  },
  {
    name: 'list_inquiry_ai_drafts',
    description: 'List AI drafts for one event inquiry, newest first',
    inputSchema: { id: z.string() },
    run: ({ id }) => apiRequest('GET', `/api/event-inquiries/${id}/ai-drafts`),
  },
  {
    name: 'generate_ai_draft',
    description: 'Ask Claude to draft the next reply on an event inquiry now (does not send; supersedes any pending draft; can take up to ~40 seconds)',
    inputSchema: { id: z.string() },
    run: ({ id }) => apiRequest('POST', `/api/event-inquiries/${id}/ai-drafts`),
  },
  {
    name: 'approve_ai_draft',
    description: 'Approve a pending AI draft and email it to the guest, optionally with an edited body (moves status to "contacted" if it was "new")',
    inputSchema: { id: z.string(), draft_id: z.string(), body: z.string().optional() },
    run: ({ id, draft_id, body }) => apiRequest('POST', `/api/event-inquiries/${id}/ai-drafts/${draft_id}/approve`, { body: body ? { body } : {} }),
  },
  {
    name: 'reject_ai_draft',
    description: 'Reject a pending AI draft so it is never sent',
    inputSchema: { id: z.string(), draft_id: z.string(), reason: z.string().optional() },
    run: ({ id, draft_id, reason }) => apiRequest('POST', `/api/event-inquiries/${id}/ai-drafts/${draft_id}/reject`, { body: reason ? { reason } : {} }),
  },
  {
    name: 'get_property',
    description: 'The property (venue/org) this API key operates for: id, name, currency, timezone',
    inputSchema: {},
    run: () => apiRequest('GET', '/api/property/me'),
  },
  {
    name: 'get_ai_reply_settings',
    description: "The property's AI enquiry-reply settings: mode (off/draft/auto), instructions, auto_send_min_score, and whether the feature is configured on this server",
    inputSchema: {},
    run: () => apiRequest('GET', '/api/property/ai-replies'),
  },
  {
    name: 'set_ai_reply_instructions',
    description: 'Set the venue knowledge the AI may state facts from when drafting enquiry replies -- capacities, packages, pricing, policies, tone (max 8000 chars; null clears). Replaces the whole text, so read get_ai_reply_settings first and merge. Mode and the auto-send threshold are dashboard-admin only.',
    inputSchema: { instructions: z.string().nullable().describe('The full replacement instructions text, or null to clear') },
    run: ({ instructions }) => apiRequest('PUT', '/api/property/ai-replies/instructions', { body: { instructions } }),
  },
  {
    name: 'list_spas',
    description: 'List spas for this property',
    inputSchema: {},
    run: () => apiRequest('GET', '/api/spa'),
  },
  {
    name: 'get_spa',
    description: 'Get a spa by id',
    inputSchema: { id: z.string() },
    run: ({ id }) => apiRequest('GET', `/api/spa/${id}`),
  },
  {
    name: 'create_spa',
    description: 'Create a spa',
    inputSchema: {
      name: z.string(),
      description: z.string().optional(),
      phone: z.string().optional(),
      slot_interval_minutes: z.number().int().optional().describe('Step between computed availability times; default 15'),
      contact_email: z.string().optional().describe('Reply-to on booking confirmation/cancellation emails'),
      address: z.string().optional().describe('Shown in booking confirmation/cancellation emails'),
    },
    run: (args) => apiRequest('POST', '/api/spa', { body: args }),
  },
  {
    name: 'update_spa',
    description: 'Update a spa. Set status to "inactive" to delete it — there is no hard-delete endpoint.',
    inputSchema: {
      id: z.string(),
      name: z.string().optional(),
      description: z.string().optional(),
      phone: z.string().optional(),
      status: z.enum(['active', 'inactive']).optional(),
      slot_interval_minutes: z.number().int().optional(),
      contact_email: z.string().optional(),
      address: z.string().optional(),
    },
    run: ({ id, ...body }) => apiRequest('PUT', `/api/spa/${id}`, { body }),
  },
  {
    name: 'list_spa_therapist_hours',
    description: "List a therapist's weekly working hours",
    inputSchema: { spa_id: z.string(), id: z.string() },
    run: ({ spa_id, id }) => apiRequest('GET', `/api/spa/${spa_id}/therapists/${id}/hours`),
  },
  {
    name: 'set_spa_therapist_hours',
    description: "Replace a therapist's full weekly working hours (drives computed availability). Omitting a day means the therapist doesn't work it.",
    inputSchema: {
      spa_id: z.string(),
      id: z.string(),
      hours: z.array(z.object({
        day_of_week: z.number().int().min(1).max(7).describe('ISO day: 1 = Monday, 7 = Sunday'),
        start_time: z.string().describe('HH:MM'),
        end_time: z.string().describe('HH:MM'),
      })),
    },
    run: ({ spa_id, id, hours }) => apiRequest('PUT', `/api/spa/${spa_id}/therapists/${id}/hours`, { body: { hours } }),
  },
  {
    name: 'list_spa_therapist_time_off',
    description: "List a therapist's whole-day time off, optionally filtered by date range",
    inputSchema: { spa_id: z.string(), id: z.string(), from: z.string().optional(), to: z.string().optional() },
    run: ({ spa_id, id, ...query }) => apiRequest('GET', `/api/spa/${spa_id}/therapists/${id}/time-off`, { query }),
  },
  {
    name: 'create_spa_therapist_time_off',
    description: 'Block out whole days for a therapist (holiday, sick day, etc.)',
    inputSchema: {
      spa_id: z.string(),
      id: z.string(),
      start_date: z.string().describe('YYYY-MM-DD'),
      end_date: z.string().describe('YYYY-MM-DD'),
      reason: z.string().optional(),
    },
    run: ({ spa_id, id, ...body }) => apiRequest('POST', `/api/spa/${spa_id}/therapists/${id}/time-off`, { body }),
  },
  {
    name: 'delete_spa_therapist_time_off',
    description: 'Remove a therapist time-off entry',
    inputSchema: { spa_id: z.string(), id: z.string(), offId: z.string() },
    run: ({ spa_id, id, offId }) => apiRequest('DELETE', `/api/spa/${spa_id}/therapists/${id}/time-off/${offId}`),
  },
  {
    name: 'search_spa_availability',
    description: 'Computed bookable start times for a treatment across a date range, duration- and overlap-aware, based on therapist working hours (not the legacy slot flow)',
    inputSchema: {
      spa_id: z.string(),
      from: z.string().describe('YYYY-MM-DD'),
      to: z.string().describe('YYYY-MM-DD, max 31 days after from'),
      treatment_id: z.string(),
      therapist_id: z.string().optional().describe('Omit to see availability across every active therapist'),
    },
    run: ({ spa_id, ...query }) => apiRequest('GET', `/api/spa/${spa_id}/availability`, { query }),
  },
  {
    name: 'list_spa_treatments',
    description: 'List treatments offered by a spa',
    inputSchema: { spa_id: z.string() },
    run: ({ spa_id }) => apiRequest('GET', `/api/spa/${spa_id}/treatments`),
  },
  {
    name: 'create_spa_treatment',
    description: 'Create a spa treatment',
    inputSchema: {
      spa_id: z.string(),
      name: z.string(),
      description: z.string().optional(),
      duration_mins: z.number().int(),
      price: z.number(),
    },
    run: ({ spa_id, ...body }) => apiRequest('POST', `/api/spa/${spa_id}/treatments`, { body }),
  },
  {
    name: 'update_spa_treatment',
    description: 'Update a spa treatment. Set status to "inactive" to delete it — there is no hard-delete endpoint.',
    inputSchema: {
      spa_id: z.string(),
      id: z.string(),
      name: z.string().optional(),
      description: z.string().optional(),
      duration_mins: z.number().int().optional(),
      price: z.number().optional(),
      status: z.enum(['active', 'inactive']).optional(),
    },
    run: ({ spa_id, id, ...body }) => apiRequest('PUT', `/api/spa/${spa_id}/treatments/${id}`, { body }),
  },
  {
    name: 'list_spa_therapists',
    description: 'List therapists at a spa',
    inputSchema: { spa_id: z.string() },
    run: ({ spa_id }) => apiRequest('GET', `/api/spa/${spa_id}/therapists`),
  },
  {
    name: 'create_spa_therapist',
    description: 'Create a spa therapist',
    inputSchema: { spa_id: z.string(), name: z.string() },
    run: ({ spa_id, ...body }) => apiRequest('POST', `/api/spa/${spa_id}/therapists`, { body }),
  },
  {
    name: 'update_spa_therapist',
    description: 'Update a spa therapist. Set status to "inactive" to delete it — there is no hard-delete endpoint.',
    inputSchema: {
      spa_id: z.string(),
      id: z.string(),
      name: z.string().optional(),
      status: z.enum(['active', 'inactive']).optional(),
    },
    run: ({ spa_id, id, ...body }) => apiRequest('PUT', `/api/spa/${spa_id}/therapists/${id}`, { body }),
  },
  {
    name: 'list_spa_slots',
    description: 'List a spa\'s appointment slots, optionally filtered by date range, therapist, or treatment',
    inputSchema: {
      spa_id: z.string(),
      date: z.string().optional(),
      from: z.string().optional(),
      to: z.string().optional(),
      therapist_id: z.string().optional(),
      treatment_id: z.string().optional(),
    },
    run: ({ spa_id, ...query }) => apiRequest('GET', `/api/spa/${spa_id}/slots`, { query }),
  },
  {
    name: 'bulk_create_spa_slots',
    description: 'Bulk-create appointment slots for a therapist/treatment across a date range and list of times',
    inputSchema: {
      spa_id: z.string(),
      therapist_id: z.string(),
      treatment_id: z.string(),
      from: z.string().describe('YYYY-MM-DD'),
      to: z.string().describe('YYYY-MM-DD'),
      times: z.array(z.string()).describe('e.g. ["09:00", "10:00"]'),
    },
    run: ({ spa_id, ...body }) => apiRequest('POST', `/api/spa/${spa_id}/slots/bulk`, { body }),
  },
  {
    name: 'search_spa_slots',
    description: 'Search available spa slots for a date, optionally filtered by treatment',
    inputSchema: { spa_id: z.string(), date: z.string(), treatment_id: z.string().optional() },
    run: ({ spa_id, ...query }) => apiRequest('GET', `/api/spa/${spa_id}/slots/search`, { query }),
  },
  {
    name: 'update_spa_slot',
    description: 'Update a spa slot\'s status',
    inputSchema: { spa_id: z.string(), id: z.string(), status: z.string() },
    run: ({ spa_id, id, status }) => apiRequest('PUT', `/api/spa/${spa_id}/slots/${id}`, { body: { status } }),
  },
  {
    name: 'list_spa_appointments',
    description: 'List appointments at a spa, optionally filtered by date, status, guest, or therapist',
    inputSchema: {
      spa_id: z.string(),
      date: z.string().optional(),
      status: z.string().optional(),
      guest_id: z.string().optional(),
      clerk_user_id: z.string().optional(),
      therapist_id: z.string().optional(),
    },
    run: ({ spa_id, ...query }) => apiRequest('GET', `/api/spa/${spa_id}/appointments`, { query }),
  },
  {
    name: 'get_spa_appointment',
    description: 'Get a spa appointment by id',
    inputSchema: { spa_id: z.string(), id: z.string() },
    run: ({ spa_id, id }) => apiRequest('GET', `/api/spa/${spa_id}/appointments/${id}`),
  },
  {
    name: 'create_spa_appointment',
    description: 'Book a spa appointment. Preferred: treatment_id + date + time (computed against working hours, therapist_id optional -- omit to auto-pick whoever is free). Legacy: slot_id alone, against a pre-generated spa_slot. Provide one or the other, not both. A confirmation email sends automatically when contact_email is given.',
    inputSchema: {
      spa_id: z.string(),
      slot_id: z.string().optional().describe('Legacy flow: book this pre-generated slot directly'),
      treatment_id: z.string().optional().describe('Computed flow: required with date and time'),
      therapist_id: z.string().optional().describe('Computed flow: omit to auto-pick the first free therapist'),
      date: z.string().optional().describe('Computed flow: YYYY-MM-DD'),
      time: z.string().optional().describe('Computed flow: HH:MM'),
      guest_id: z.string().optional(),
      clerk_user_id: z.string().optional(),
      contact_name: z.string(),
      contact_email: z.string().optional(),
      contact_phone: z.string().optional(),
      notes: z.string().optional(),
      branding: BRANDING_SCHEMA.describe('Styles the confirmation email; relayed, never stored'),
      cancel_url: z.string().optional().describe('http(s) URL for the guest to cancel; may contain {id}'),
    },
    run: ({ spa_id, ...body }) => apiRequest('POST', `/api/spa/${spa_id}/appointments`, { body }),
  },
  {
    name: 'update_spa_appointment',
    description: 'Update a spa appointment (e.g. set status to "cancelled" to cancel it)',
    inputSchema: {
      spa_id: z.string(),
      id: z.string(),
      status: z.string().optional(),
      notes: z.string().optional(),
      branding: BRANDING_SCHEMA.describe('Styles the cancellation email when status becomes "cancelled"; relayed, never stored'),
    },
    run: ({ spa_id, id, ...body }) => apiRequest('PUT', `/api/spa/${spa_id}/appointments/${id}`, { body }),
  },
  {
    name: 'list_equipment',
    description: 'List equipment for hire, optionally filtered by type',
    inputSchema: { type: z.string().optional() },
    run: (args) => apiRequest('GET', '/api/equipment', { query: args }),
  },
  {
    name: 'create_equipment',
    description: 'Create a hireable equipment item',
    inputSchema: {
      name: z.string(),
      type: z.string(),
      description: z.string().optional(),
      quantity: z.number().int(),
      price_per_day: z.number().optional(),
      price_per_hour: z.number().optional(),
    },
    run: (args) => apiRequest('POST', '/api/equipment', { body: args }),
  },
  {
    name: 'update_equipment',
    description: 'Update an equipment item. Set status to "inactive" to delete it — there is no hard-delete endpoint.',
    inputSchema: {
      id: z.string(),
      name: z.string().optional(),
      type: z.string().optional(),
      description: z.string().optional(),
      quantity: z.number().int().optional(),
      price_per_day: z.number().optional(),
      price_per_hour: z.number().optional(),
      status: z.enum(['active', 'inactive']).optional(),
    },
    run: ({ id, ...body }) => apiRequest('PUT', `/api/equipment/${id}`, { body }),
  },
  {
    name: 'search_equipment',
    description: 'Search equipment availability for a date, optionally filtered by type or minimum quantity',
    inputSchema: { date: z.string(), type: z.string().optional(), quantity: z.number().int().optional() },
    run: (args) => apiRequest('GET', '/api/equipment/search', { query: args }),
  },
  {
    name: 'list_equipment_hires',
    description: 'List equipment hire bookings, optionally filtered by date, status, guest, golf booking, or equipment',
    inputSchema: {
      date: z.string().optional(),
      status: z.string().optional(),
      guest_id: z.string().optional(),
      golf_booking_id: z.string().optional(),
      equipment_id: z.string().optional(),
    },
    run: (args) => apiRequest('GET', '/api/equipment/hires', { query: args }),
  },
  {
    name: 'create_equipment_hire',
    description: 'Hire equipment for a guest. rate_type defaults to "per_day"; total_price is computed server-side from the equipment\'s rate.',
    inputSchema: {
      equipment_id: z.string(),
      guest_id: z.string().optional(),
      contact_name: z.string(),
      contact_email: z.string().optional(),
      contact_phone: z.string().optional(),
      hire_date: z.string().describe('YYYY-MM-DD'),
      start_time: z.string().optional(),
      quantity: z.number().int(),
      rate_type: z.enum(['per_day', 'per_hour']).optional(),
      duration: z.number().optional(),
      notes: z.string().optional(),
      golf_booking_id: z.string().optional(),
    },
    run: (args) => apiRequest('POST', '/api/equipment/hires', { body: args }),
  },
  {
    name: 'update_equipment_hire',
    description: 'Update an equipment hire (e.g. set status to "cancelled" to cancel it)',
    inputSchema: { id: z.string(), status: z.string().optional(), notes: z.string().optional() },
    run: ({ id, ...body }) => apiRequest('PUT', `/api/equipment/hires/${id}`, { body }),
  },
  {
    name: 'list_golf_courses',
    description: 'List golf courses for this property',
    inputSchema: {},
    run: () => apiRequest('GET', '/api/golf/courses'),
  },
  {
    name: 'create_golf_course',
    description: 'Create a golf course',
    inputSchema: {
      name: z.string(),
      description: z.string().optional(),
      holes: z.number().int(),
      price_per_player: z.number(),
    },
    run: (args) => apiRequest('POST', '/api/golf/courses', { body: args }),
  },
  {
    name: 'update_golf_course',
    description: 'Update a golf course. Set status to "inactive" to delete it — there is no hard-delete endpoint.',
    inputSchema: {
      id: z.string(),
      name: z.string().optional(),
      description: z.string().optional(),
      holes: z.number().int().optional(),
      price_per_player: z.number().optional(),
      status: z.enum(['active', 'inactive']).optional(),
    },
    run: ({ id, ...body }) => apiRequest('PUT', `/api/golf/courses/${id}`, { body }),
  },
  {
    name: 'bulk_create_tee_times',
    description: 'Bulk-create tee times for a course across a date range and list of times',
    inputSchema: {
      course_id: z.string(),
      from: z.string().describe('YYYY-MM-DD'),
      to: z.string().describe('YYYY-MM-DD'),
      times: z.array(z.string()).describe('e.g. ["08:00", "08:10"]'),
      max_players: z.number().int(),
    },
    run: (args) => apiRequest('POST', '/api/golf/tee-times/bulk', { body: args }),
  },
  {
    name: 'search_tee_times',
    description: 'Search available tee times for a date or date range, optionally filtered by course or minimum spots',
    inputSchema: {
      date: z.string().optional().describe('Single date; omit and use from/to for a range'),
      from: z.string().optional(),
      to: z.string().optional(),
      course_id: z.string().optional(),
      players: z.number().int().optional(),
    },
    run: (args) => apiRequest('GET', '/api/golf/tee-times/search', { query: args }),
  },
  {
    name: 'list_golf_bookings',
    description: 'List golf bookings, optionally filtered by date, status, or guest',
    inputSchema: {
      date: z.string().optional(),
      status: z.string().optional(),
      guest_id: z.string().optional(),
      skip: z.number().int().optional(),
      take: z.number().int().optional(),
    },
    run: (args) => apiRequest('GET', '/api/golf/bookings', { query: args }),
  },
  {
    name: 'create_golf_booking',
    description: 'Book a tee time. total_price is computed server-side from the course rate and player count.',
    inputSchema: {
      tee_time_id: z.string(),
      guest_id: z.string().optional(),
      contact_name: z.string(),
      contact_email: z.string().optional(),
      contact_phone: z.string().optional(),
      players: z.number().int(),
      notes: z.string().optional(),
    },
    run: (args) => apiRequest('POST', '/api/golf/bookings', { body: args }),
  },
  {
    name: 'update_golf_booking',
    description: 'Update a golf booking (e.g. set status to "cancelled" to cancel it)',
    inputSchema: {
      id: z.string(),
      status: z.string().optional(),
      notes: z.string().optional(),
      contact_name: z.string().optional(),
      contact_email: z.string().optional(),
      contact_phone: z.string().optional(),
    },
    run: ({ id, ...body }) => apiRequest('PUT', `/api/golf/bookings/${id}`, { body }),
  },
  {
    name: 'list_extras',
    description: 'List the extras catalogue for this property',
    inputSchema: {},
    run: () => apiRequest('GET', '/api/extras'),
  },
  {
    name: 'create_extra',
    description: 'Create an extra catalogue item',
    inputSchema: { name: z.string(), description: z.string().optional(), price: z.number() },
    run: (args) => apiRequest('POST', '/api/extras', { body: args }),
  },
  {
    name: 'update_extra',
    description: 'Update an extra catalogue item. Set status to "inactive" to delete it — there is no hard-delete endpoint.',
    inputSchema: {
      id: z.string(),
      name: z.string().optional(),
      description: z.string().optional(),
      price: z.number().optional(),
      status: z.enum(['active', 'inactive']).optional(),
    },
    run: ({ id, ...body }) => apiRequest('PUT', `/api/extras/${id}`, { body }),
  },
  {
    name: 'list_booking_extras',
    description: 'List extras added to a room booking',
    inputSchema: { booking_id: z.string() },
    run: ({ booking_id }) => apiRequest('GET', `/api/extras/booking/${booking_id}`),
  },
  {
    name: 'add_booking_extra',
    description: 'Add an extra to a room booking',
    inputSchema: { booking_id: z.string(), extra_id: z.string(), quantity: z.number().int().optional() },
    run: ({ booking_id, ...body }) => apiRequest('POST', `/api/extras/booking/${booking_id}`, { body }),
  },
  {
    name: 'remove_booking_extra',
    description: 'Remove an extra from a room booking',
    inputSchema: { booking_id: z.string(), id: z.string() },
    run: ({ booking_id, id }) => apiRequest('DELETE', `/api/extras/booking/${booking_id}/${id}`),
  },
  // Beach club create/update routes (create_bed, update_bed, create_booking,
  // update_booking) use the older requireApiKey middleware -- a single
  // global secret (process.env.API_KEY), not the per-property X-Api-Key an
  // MCP client authenticates with (see OTA/src/middleware/apiKey.js vs
  // authenticateOrApiKey). Those writes would always 401 through this MCP
  // server, so only the two unauthenticated read routes are exposed here.
  // (Note: listBeds/searchBeds also aren't property-scoped in the
  // controller -- a separate, pre-existing gap, not introduced by this.)
  {
    name: 'list_beach_beds',
    description: 'List beach club beds, optionally filtered by zone',
    inputSchema: { zone: z.string().optional() },
    run: (args) => apiRequest('GET', '/api/beach-club/beds', { query: args }),
  },
  {
    name: 'search_beach_beds',
    description: 'Search available beach club beds for a date, optionally filtered by zone',
    inputSchema: { date: z.string(), zone: z.string().optional() },
    run: (args) => apiRequest('GET', '/api/beach-club/beds/search', { query: args }),
  },
  ];
}

module.exports = { createTools };
